version: "3.7"
services:
  app:
    build:
      context: .
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://db/my_coffee
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=my_coffee
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      
volumes:
  db-data:
 